#define SERIAL_SPEED 115200

#define BUTTON_HOLD_INTERVAL 2000
#define BUTTON_DEBOUNCE_INTERVAL 20
#define MUX_PROPAGATION_DELAY 100

#define STEPS_PER_REVOLUTION 2048

#define ENCODER_DELTA 5

// Vertical movement constnats
#define TICKS_BELOW_RECORD 100